# For a complete introduction, visit the official docs at: https://espanso.org/docs/
matches:
  - trigger: "Qshell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

