
[opener]
edit = [
	{ run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'nvim %*',    block = true,  desc = "nvim",           for = "windows" },
	{ run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
	{ run = 'code -w %*', block = true,  desc = "code (block)",   for = "windows" },
]

[open]
prepend_rules = [
	{ mime = "text/*", use = [ "edit", "open", "reveal" ] },
]

[[plugin.prepend_preloaders]]
name = "/home/lutfi/drives/lutfi221/**"
run  = "noop"

[[plugin.prepend_previewers]]
name = "/home/lutfi/drives/lutfi221/**"
run  = "noop"
